### ISSUE TITLE
Use in docker

### ISSUE THREAD

**Issue by Clan-Utility** [iotblue/emq_kafka_bridge#23]
When I put this plugin in docker, and set environment in docker-composer.yml as:

    EMQ_KAFKA__HOST: 'localhost' // or any unaccessible IP

The message does not get delivered to Kafka.

If set:

     EMQ_KAFKA__HOST: 'host.docker.internal' // or IP of the kafka container

It keeps giving the following error:

emqtt     | 01:28:44.584 [error] gen_server <0.1426.0> terminated with reason: {timeout,{gen_fsm,sync_send_event,[<0.1431.0>,prepare]}}
emqtt     | (61618531fa3e@172.19.0.4)1> 01:28:44.585 [error] CRASH REPORT Process <0.1426.0> with 0 neighbours exited with reason: {timeout,{gen_fsm,sync_send_event,[<0.1431.0>,prepare]}} in gen_server2:terminate/3 line 1157
emqtt     | (61618531fa3e@172.19.0.4)1> 01:28:44.585 [error] Supervisor 'esockd_connection_sup - <0.1263.0>' had child connection started with emqttd_client:start_link([{max_publish_rate,0},{client_idle_timeout,30000},{client_enable_stats,false},{max_clientid_len,...},...]) at <0.1426.0> exit with reason {timeout,{gen_fsm,sync_send_event,[<0.1431.0>,prepare]}} in context connection_crashed
emqtt     | (61618531fa3e@172.19.0.4)1>
emqtt     | ekaf_server:130 <0.1431.0>:downtime/2 cant handle {metadata,resp,
emqtt     |                                                    {metadata_response,1,
emqtt     |                                                     [{broker,1,
emqtt     |                                                       <<"localhost">>,9092}],
emqtt     |                                                     [{topic,<<"Event">>,0,
emqtt     |                                                       [{partition,0,0,1,
emqtt     |                                                         [{replica,1}],
emqtt     |                                                         [{isr,1}],
emqtt     |                                                         0,[]}]}]}}(61618531fa3e@172.19.0.4)1>
emqtt     | ekaf_server:130 <0.1431.0>:downtime/2 cant handle {metadata,resp,
emqtt     |                                                    {metadata_response,1,
emqtt     |                                                     [{broker,1,
emqtt     |                                                       <<"localhost">>,9092}],
emqtt     |                                                     [{topic,<<"Event">>,0,
emqtt     |                                                       [{partition,0,0,1,
emqtt     |                                                         [{replica,1}],
emqtt     |                                                         [{isr,1}],
emqtt     |                                                         0,[]}]}]}}(61618531fa3e@172.19.0.4)1> 01:28:53.740 [error] Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,[<0.1463.0>,{inet_async,#Port<0.2107>,182,{ok,<<48,59,0,40,47,82,101,55,120,86,116,54,82,108,77,120,47,79,71,65,49,48,118,82,101,115,112,67,55,69,74,78,69,116,77,67,119,47,117,112,100,97,116,101,51,50,46,54,51,49,48,55,53,52,57,53,50,53,48,52,55>>}},{client_state,{esockd_connection,[#Port<0.2107>,#Fun<esockd_transport.2.122912610>,[]]},{{172,19,0,1},33708},running,true,undefined,65536,{none,65536},{proto_state,{{172,19,0,1},33708},#Fun<emqttd_client.0.18944683>,true,<<"OGA1...">>,...},...},...]},...}}
emqtt     | (61618531fa3e@172.19.0.4)1>
emqtt     | ekaf_server:130 <0.1431.0>:downtime/2 cant handle {metadata,resp,
emqtt     |                                                    {metadata_response,1,
emqtt     |                                                     [{broker,1,
emqtt     |                                                       <<"localhost">>,9092}],
emqtt     |                                                     [{topic,<<"Event">>,0,
emqtt     |                                                       [{partition,0,0,1,
emqtt     |                                                         [{replica,1}],
emqtt     |                                                         [{isr,1}],
...

**Comment by iotblue** [comment]
First how do you run your docker container (docker cli [`docker run`], docker compose or docker swarm)

**Comment by Clan-Utility** [comment]
Here is the docker compose file, run with:

    docker-compose -f emqtt.yml up

version: '3'

services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
    hostname: zoo1
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "Payload:1:1,Event:1:1"
    depends_on:
      - zoo1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: kafka

  emqtt:
    image: emqtt:mine
    restart: unless-stopped
    ports:
      - "18083:18083"
      - "1883:1883"
    environment:
      EMQ_LOADED_PLUGINS: "emq_modules,emqx_recon,emqx_retainer,emq_reloader,emq_auth_http,emq_kafka_bridge"
      EMQ_KAFKA__HOST: "localhost"
      EMQ_KAFKA__PORT: "9092"
      EMQ_KAFKA__PARTITIONWORKERS: 1
    depends_on:
      - kafka1
    container_name: emqtt

**Comment by iotblue** [comment]
> Here is the docker compose file:
> 
> ```
> version: '3'
> 
> services:
>   zoo1:
>     image: wurstmeister/zookeeper
>     restart: unless-stopped
>     hostname: zoo1
>     ports:
>       - "2181:2181"
>     container_name: zookeeper
> 
>   kafka1:
>     image: wurstmeister/kafka
>     ports:
>       - "9092:9092"
>     environment:
>       KAFKA_ADVERTISED_HOST_NAME: "localhost"
>       KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
>       KAFKA_BROKER_ID: 1
>       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
>       KAFKA_CREATE_TOPICS: "Payload:1:1,Event:1:1"
>     depends_on:
>       - zoo1
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>     container_name: kafka
> 
>   emqtt:
>     image: emqtt:mine
>     restart: unless-stopped
>     ports:
>       - "18083:18083"
>       - "1883:1883"
>     environment:
>       EMQ_LOADED_PLUGINS: "emq_modules,emqx_recon,emqx_retainer,emq_reloader,emq_auth_http,emq_kafka_bridge"
>       EMQ_KAFKA__HOST: "localhost" 
>       EMQ_KAFKA__PORT: "9092"
>       EMQ_KAFKA__PARTITIONWORKERS: 1
>     depends_on:
>       - kafka1
>     container_name: emqtt
> ```
> 
> run with:
> 
> ```
> docker-compose -f emqtt.yml up
> ```
> 
> The following setting does not work either.
> 
> ```
> EMQ_KAFKA__HOST: "kafka" 
> ```

**Comment by iotblue** [comment]
ok may i

**Comment by iotblue** [comment]
may i propose a slight change to compose file

1. remove `container_name`
2. for `KAFKA_ADVERTISED_HOST_NAME` set it to the servicename `kafka1` and to access kafka from host client in hosts file add this line `127.0.0.1        kafka1`
3. for `EMQ_KAFKA__HOST` set it to kafka service name `kafka1`

try the below YML config

```
version: '3'

services:
  zoo1:
    image: wurstmeister/zookeeper
    restart: unless-stopped
   # hostname: zoo1
    ports:
      - "2181:2181"
    # container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka1"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "Payload:1:1,Event:1:1"
    depends_on:
      - zoo1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # container_name: kafka

  emqtt:
    image: 
    restart: unless-stopped
    ports: emqtt:mine
      - "18083:18083"
      - "1883:1883"
    environment:
      EMQ_LOADED_PLUGINS: "emq_modules,emqx_recon,emqx_retainer,emq_reloader,emq_auth_http,emq_kafka_bridge,emq_dashboard"
      EMQ_KAFKA__HOST: kafka1
      EMQ_KAFKA__PORT: 9092
      EMQ_KAFKA__PARTITIONWORKERS: 1
    depends_on:
      - kafka1
    # container_name: emqtt
```

**Comment by iotblue** [comment]
Also you can configure kafka as follow:
 
```yaml
  kafka1:
    image: wurstmeister/kafka
    ports:
      - "9094:9094"
    environment:
      HOSTNAME_COMMAND: "docker info | grep ^Name: | cut -d' ' -f 2"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "Payload:1:1,Event:1:1"
    depends_on:
      - zookeeper1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
so inside other services you can just use Kafka hostname : `kafka1` and port 9092
and from host machine you can connect using `localhost` and port 9094
